### ISSUE TITLE
jialin7878.PNG: should be .png

### ISSUE THREAD

**Issue by damithc** [AY2021S1-CS2103-T14-2/tp#55]
The extension should be .png (not .PNG)
![image](https://user-images.githubusercontent.com/1673303/95606850-88663c00-0a8d-11eb-90dc-6088bf1d0675.png)

**Comment by damithc** [comment]
Also, the profile photo name doesn't match the GitHub username for one of your team members.

**Comment by CalistaIo** [comment]
Issue rectified
